[package]
name = "udpnull"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
rayon = "1.8"
clap = { version = "4.4", features = ["derive"] }
socket2 = "0.5"
rand = "0.9"
num_cpus = "1.17"
rand_chacha = "0.9"
